delete from CURRENCIES;
insert into CURRENCIES values (784,'AED','UAE Dirham');
insert into CURRENCIES values (971,'AFN','Afghani');
insert into CURRENCIES values (008,'ALL','Lek');
insert into CURRENCIES values (051,'AMD','Armenian Dram');
insert into CURRENCIES values (532,'ANG','Netherlands Antillean Guilder');
insert into CURRENCIES values (973,'AOA','Kwanza');
insert into CURRENCIES values (032,'ARS','Argentine Peso');
insert into CURRENCIES values (036,'AUD','Australian Dollar');
insert into CURRENCIES values (533,'AWG','Aruban Florin');
insert into CURRENCIES values (944,'AZN','Azerbaijan Manat');
insert into CURRENCIES values (977,'BAM','Convertible Mark');
insert into CURRENCIES values (052,'BBD','Barbados Dollar');
insert into CURRENCIES values (050,'BDT','Taka');
insert into CURRENCIES values (975,'BGN','Bulgarian Lev');
insert into CURRENCIES values (048,'BHD','Bahraini Dinar');
insert into CURRENCIES values (108,'BIF','Burundi Franc');
insert into CURRENCIES values (060,'BMD','Bermudian Dollar');
insert into CURRENCIES values (096,'BND','Brunei Dollar');
insert into CURRENCIES values (068,'BOB','Boliviano');
insert into CURRENCIES values (984,'BOV','Mvdol');
insert into CURRENCIES values (986,'BRL','Brazilian Real');
insert into CURRENCIES values (044,'BSD','Bahamian Dollar');
insert into CURRENCIES values (064,'BTN','Ngultrum');
insert into CURRENCIES values (072,'BWP','Pula');
insert into CURRENCIES values (933,'BYN','Belarusian Ruble');
insert into CURRENCIES values (084,'BZD','Belize Dollar');
insert into CURRENCIES values (124,'CAD','Canadian Dollar');
insert into CURRENCIES values (976,'CDF','Congolese Franc');
insert into CURRENCIES values (947,'CHE','WIR Euro');
insert into CURRENCIES values (756,'CHF','Swiss Franc');
insert into CURRENCIES values (948,'CHW','WIR Franc');
insert into CURRENCIES values (990,'CLF','Unidad de Fomento');
insert into CURRENCIES values (152,'CLP','Chilean Peso');
insert into CURRENCIES values (156,'CNY','Yuan Renminbi');
insert into CURRENCIES values (170,'COP','Colombian Peso');
insert into CURRENCIES values (970,'COU','Unidad de Valor Real');
insert into CURRENCIES values (188,'CRC','Costa Rican Colon');
insert into CURRENCIES values (931,'CUC','Peso Convertible');
insert into CURRENCIES values (192,'CUP','Cuban Peso');
insert into CURRENCIES values (132,'CVE','Cabo Verde Escudo');
insert into CURRENCIES values (203,'CZK','Czech Koruna');
insert into CURRENCIES values (262,'DJF','Djibouti Franc');
insert into CURRENCIES values (208,'DKK','Danish Krone');
insert into CURRENCIES values (214,'DOP','Dominican Peso');
insert into CURRENCIES values (012,'DZD','Algerian Dinar');
insert into CURRENCIES values (818,'EGP','Egyptian Pound');
insert into CURRENCIES values (232,'ERN','Nakfa');
insert into CURRENCIES values (230,'ETB','Ethiopian Birr');
insert into CURRENCIES values (978,'EUR','Euro');
insert into CURRENCIES values (242,'FJD','Fiji Dollar');
insert into CURRENCIES values (238,'FKP','Falkland Islands Pound');
insert into CURRENCIES values (826,'GBP','Pound Sterling');
insert into CURRENCIES values (981,'GEL','Lari');
insert into CURRENCIES values (936,'GHS','Ghana Cedi');
insert into CURRENCIES values (292,'GIP','Gibraltar Pound');
insert into CURRENCIES values (270,'GMD','Dalasi');
insert into CURRENCIES values (324,'GNF','Guinean Franc');
insert into CURRENCIES values (320,'GTQ','Quetzal');
insert into CURRENCIES values (328,'GYD','Guyana Dollar');
insert into CURRENCIES values (344,'HKD','Hong Kong Dollar');
insert into CURRENCIES values (340,'HNL','Lempira');
insert into CURRENCIES values (191,'HRK','Kuna');
insert into CURRENCIES values (332,'HTG','Gourde');
insert into CURRENCIES values (348,'HUF','Forint');
insert into CURRENCIES values (360,'IDR','Rupiah');
insert into CURRENCIES values (376,'ILS','New Israeli Sheqel');
insert into CURRENCIES values (356,'INR','Indian Rupee');
insert into CURRENCIES values (368,'IQD','Iraqi Dinar');
insert into CURRENCIES values (364,'IRR','Iranian Rial');
insert into CURRENCIES values (352,'ISK','Iceland Krona');
insert into CURRENCIES values (388,'JMD','Jamaican Dollar');
insert into CURRENCIES values (400,'JOD','Jordanian Dinar');
insert into CURRENCIES values (392,'JPY','Yen');
insert into CURRENCIES values (404,'KES','Kenyan Shilling');
insert into CURRENCIES values (417,'KGS','Som');
insert into CURRENCIES values (116,'KHR','Riel');
insert into CURRENCIES values (174,'KMF','Comorian Franc ');
insert into CURRENCIES values (408,'KPW','North Korean Won');
insert into CURRENCIES values (410,'KRW','Won');
insert into CURRENCIES values (414,'KWD','Kuwaiti Dinar');
insert into CURRENCIES values (136,'KYD','Cayman Islands Dollar');
insert into CURRENCIES values (398,'KZT','Tenge');
insert into CURRENCIES values (418,'LAK','Lao Kip');
insert into CURRENCIES values (422,'LBP','Lebanese Pound');
insert into CURRENCIES values (144,'LKR','Sri Lanka Rupee');
insert into CURRENCIES values (430,'LRD','Liberian Dollar');
insert into CURRENCIES values (426,'LSL','Loti');
insert into CURRENCIES values (434,'LYD','Libyan Dinar');
insert into CURRENCIES values (504,'MAD','Moroccan Dirham');
insert into CURRENCIES values (498,'MDL','Moldovan Leu');
insert into CURRENCIES values (969,'MGA','Malagasy Ariary');
insert into CURRENCIES values (807,'MKD','Denar');
insert into CURRENCIES values (104,'MMK','Kyat');
insert into CURRENCIES values (496,'MNT','Tugrik');
insert into CURRENCIES values (446,'MOP','Pataca');
insert into CURRENCIES values (929,'MRU','Ouguiya');
insert into CURRENCIES values (480,'MUR','Mauritius Rupee');
insert into CURRENCIES values (462,'MVR','Rufiyaa');
insert into CURRENCIES values (454,'MWK','Malawi Kwacha');
insert into CURRENCIES values (484,'MXN','Mexican Peso');
insert into CURRENCIES values (979,'MXV','Mexican Unidad de Inversion (UDI)');
insert into CURRENCIES values (458,'MYR','Malaysian Ringgit');
insert into CURRENCIES values (943,'MZN','Mozambique Metical');
insert into CURRENCIES values (516,'NAD','Namibia Dollar');
insert into CURRENCIES values (566,'NGN','Naira');
insert into CURRENCIES values (558,'NIO','Cordoba Oro');
insert into CURRENCIES values (578,'NOK','Norwegian Krone');
insert into CURRENCIES values (524,'NPR','Nepalese Rupee');
insert into CURRENCIES values (554,'NZD','New Zealand Dollar');
insert into CURRENCIES values (512,'OMR','Rial Omani');
insert into CURRENCIES values (590,'PAB','Balboa');
insert into CURRENCIES values (604,'PEN','Sol');
insert into CURRENCIES values (598,'PGK','Kina');
insert into CURRENCIES values (608,'PHP','Philippine Peso');
insert into CURRENCIES values (586,'PKR','Pakistan Rupee');
insert into CURRENCIES values (985,'PLN','Zloty');
insert into CURRENCIES values (600,'PYG','Guarani');
insert into CURRENCIES values (634,'QAR','Qatari Rial');
insert into CURRENCIES values (946,'RON','Romanian Leu');
insert into CURRENCIES values (941,'RSD','Serbian Dinar');
insert into CURRENCIES values (643,'RUB','Russian Ruble');
insert into CURRENCIES values (646,'RWF','Rwanda Franc');
insert into CURRENCIES values (682,'SAR','Saudi Riyal');
insert into CURRENCIES values (090,'SBD','Solomon Islands Dollar');
insert into CURRENCIES values (690,'SCR','Seychelles Rupee');
insert into CURRENCIES values (938,'SDG','Sudanese Pound');
insert into CURRENCIES values (752,'SEK','Swedish Krona');
insert into CURRENCIES values (702,'SGD','Singapore Dollar');
insert into CURRENCIES values (654,'SHP','Saint Helena Pound');
insert into CURRENCIES values (694,'SLL','Leone');
insert into CURRENCIES values (706,'SOS','Somali Shilling');
insert into CURRENCIES values (968,'SRD','Surinam Dollar');
insert into CURRENCIES values (728,'SSP','South Sudanese Pound');
insert into CURRENCIES values (930,'STN','Dobra');
insert into CURRENCIES values (222,'SVC','El Salvador Colon');
insert into CURRENCIES values (760,'SYP','Syrian Pound');
insert into CURRENCIES values (748,'SZL','Lilangeni');
insert into CURRENCIES values (764,'THB','Baht');
insert into CURRENCIES values (972,'TJS','Somoni');
insert into CURRENCIES values (934,'TMT','Turkmenistan New Manat');
insert into CURRENCIES values (788,'TND','Tunisian Dinar');
insert into CURRENCIES values (776,'TOP','Pa’anga');
insert into CURRENCIES values (949,'TRY','Turkish Lira');
insert into CURRENCIES values (780,'TTD','Trinidad and Tobago Dollar');
insert into CURRENCIES values (901,'TWD','New Taiwan Dollar');
insert into CURRENCIES values (834,'TZS','Tanzanian Shilling');
insert into CURRENCIES values (980,'UAH','Hryvnia');
insert into CURRENCIES values (800,'UGX','Uganda Shilling');
insert into CURRENCIES values (840,'USD','US Dollar');
insert into CURRENCIES values (997,'USN','US Dollar (Next day)');
insert into CURRENCIES values (940,'UYI','Uruguay Peso en Unidades Indexadas (UI)');
insert into CURRENCIES values (858,'UYU','Peso Uruguayo');
insert into CURRENCIES values (927,'UYW','Unidad Previsional');
insert into CURRENCIES values (860,'UZS','Uzbekistan Sum');
insert into CURRENCIES values (928,'VES','Bolívar Soberano');
insert into CURRENCIES values (704,'VND','Dong');
insert into CURRENCIES values (548,'VUV','Vatu');
insert into CURRENCIES values (882,'WST','Tala');
insert into CURRENCIES values (950,'XAF','CFA Franc BEAC');
insert into CURRENCIES values (961,'XAG','Silver');
insert into CURRENCIES values (959,'XAU','Gold');
insert into CURRENCIES values (955,'XBA','Bond Markets Unit European Composite Unit (EURCO)');
insert into CURRENCIES values (956,'XBB','Bond Markets Unit European Monetary Unit (E.M.U.-6)');
insert into CURRENCIES values (957,'XBC','Bond Markets Unit European Unit of Account 9 (E.U.A.-9)');
insert into CURRENCIES values (958,'XBD','Bond Markets Unit European Unit of Account 17 (E.U.A.-17)');
insert into CURRENCIES values (951,'XCD','East Caribbean Dollar');
insert into CURRENCIES values (960,'XDR','SDR (Special Drawing Right)');
insert into CURRENCIES values (952,'XOF','CFA Franc BCEAO');
insert into CURRENCIES values (964,'XPD','Palladium');
insert into CURRENCIES values (953,'XPF','CFP Franc');
insert into CURRENCIES values (962,'XPT','Platinum');
insert into CURRENCIES values (994,'XSU','Sucre');
insert into CURRENCIES values (963,'XTS','Codes specifically reserved for testing purposes');
insert into CURRENCIES values (965,'XUA','ADB Unit of Account');
insert into CURRENCIES values (886,'YER','Yemeni Rial');
insert into CURRENCIES values (710,'ZAR','Rand');
insert into CURRENCIES values (967,'ZMW','Zambian Kwacha');
insert into CURRENCIES values (932,'ZWL','Zimbabwe Dollar');
