CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS REPORTS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    DATE DATE NOT NULL,
    MESSAGE VARCHAR(1024) NOT NULL,
    UNIQUE(USER_ID,DATE,MESSAGE)
);

